#!/usr/bin/env bash
set -euo pipefail

BASELINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UPDATE_LOG="$BASELINE_DIR/update-loop/update-log.md"
SNAPSHOT="$BASELINE_DIR/update-loop/baseline-snapshot.md"
TODAY=$(date +%Y-%m-%d)

echo "=== Baseline Update — $TODAY ==="
echo ""

# Last update date
if grep -q "^## " "$UPDATE_LOG" 2>/dev/null; then
  LAST_UPDATE=$(grep "^## " "$UPDATE_LOG" | head -1 | sed 's/## //')
  echo "Last update: $LAST_UPDATE"
else
  LAST_UPDATE="never"
  echo "Last update: never (first run)"
fi

echo "Current date: $TODAY"
echo ""

# Generate baseline snapshot
echo "Generating baseline-snapshot.md..."
{
  echo "# Baseline Snapshot — $TODAY"
  echo ""
  echo "Auto-generated by run-update.sh. Do not edit manually."
  echo ""
  echo "---"
  echo ""
  while IFS= read -r f; do
    echo "## $(basename "$f")"
    echo ""
    cat "$f"
    echo ""
    echo "---"
    echo ""
  done < <(find "$BASELINE_DIR/core" -name "*.md" | sort)
} > "$SNAPSHOT"

echo "Snapshot written to: update-loop/baseline-snapshot.md"
echo ""

# Print the command to run the research agent
echo "=== Next Step ==="
echo ""
echo "Run the monthly research prompt with web search enabled."
echo "Edit the prompt first — fill in today's date and last update date:"
echo ""
echo "  Today: $TODAY"
echo "  Last update: $LAST_UPDATE"
echo ""
echo "Prompt file: update-loop/research-prompt.md"
echo "MCP review:  update-loop/mcp-review.md"
echo ""
echo "After the agent produces its JSON output:"
echo "  1. Review and approve findings"
echo "  2. Apply approved diffs"
echo "  3. Run: git add -p && git commit -m 'chore: monthly baseline update $TODAY'"
echo "  4. Append to update-loop/update-log.md:"
echo "     ## $TODAY"
echo "     [summary of changes made]"
echo ""
